name: Production
values:
  - key: baseUrl
    value: https://api.aqualink.site/graphql
    type: default
    enabled: true
  - key: token
    value: ''
    type: secret
    enabled: true
  - key: adminEmail
    value: ''
    type: secret
    enabled: true
  - key: adminPassword
    value: ''
    type: secret
    enabled: true
